"""add the profile paths

Revision ID: 7e0201e07bd1
Revises: dec515306a58
Create Date: 2021-06-23 09:13:03.938655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e0201e07bd1'
down_revision = 'dec515306a58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('post_pic_path', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('blogs', 'post_pic_path')
    # ### end Alembic commands ###
